config/routes.rb
Richardjlo::Application.routes.draw do

  root to: 'static_pages#home'
  match 'projects', to:'static_pages#projects'
  match 'resume', to:'static_pages#resume'
  match 'contact', to:'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def projects
  end

  def resume
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Richard Lo"		
		if page_title.empty?
					base_title
		else			
			"#{base_title} | #{page_title}"
		end
	end

	#highlights current page in navbar
	def active_class(page_title, cur_tab)
		active_class = "active"
		if page_title == cur_tab 
			active_class
		end
	end
		

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">    	
        <div class="container">            
        	<%= link_to "Richard J Lo", root_path, class: "brand" %>
        	<div class="nav-collapse collapse">
    			<ul class="nav">                                                  
    			    <li class="<%= active_class(yield(:title), "Projects") %>"><%= link_to "Projects", projects_path %></li>
    			    <li class="<%= active_class(yield(:title), "Resume") %>"><%= link_to "Resume", resume_path %></li>
    			    <li class="<%= active_class(yield(:title), "Contact") %>"><%= link_to "Get in Touch", contact_path %></li>
    			</ul>                    
          </div>
        </div>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
</script> 
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		
		<div class="container">			
			<%= render 'layouts/navbar' %>
			<%= yield %> 
		</div>
	</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="banner">
	<div id="line1">
		<h2>Get in touch at</h2>
	</div>		
	<div id ="line2">
		<h1>richardjosonlo@gmail.com</h1>
	</div>		

</div>

app/views/static_pages/home.html.erb
<div class="span6 offset5" id="profile">
	<div id="profile-head">
		<div id="title">
			<h1>Richard J Lo</h1>
		</div>
		<div id="subtitle">
			<h2>Behavior Designer, Entrepreneur</h2> 
		</div>
	</div>		
	<div id="profile-content"></div>
		<div id="profile-internal">
			<%= link_to "projects /", projects_path %>
			<%= link_to "resume /", resume_path %>
			<%= link_to "contact", contact_path %>
		</div>
		<div id="profile-external">
			<%= link_to "tweets", "http://twitter.com/richardjlo" , :target => "_blank"%>, 
			<%= link_to "blog", "http://blog.richardjlo.com/" , :target => "_blank"%>, 
			<%= link_to "linkedin", "http://www.linkedin.com/in/richardjlo" , :target => "_blank"%>
		</div>
</div>

app/views/static_pages/projects.html.erb
<% provide(:title, 'Projects') %>

<div class="banner offset3">
	<h1>Coming Soon!</h1>                	
</div>

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>

<div class="container resume-container">
    <div> <%= link_to "download pdf", "https://www.dropbox.com/s/8jkp81s1us5xjow/Lo.Richard.Resume.pdf", id: "download" , :target => "_blank"%> </div>
    <div class="clear"></div>
    <div class="resume-inner span10">
        <div class="resume-header">                    
            <div class="name">
                <h1>Richard J Lo</h1>
            </div>
            <div class="contact">
                <p>richardjosonlo [at] gmail [dot] com<br>
                <%= link_to "650.918.6756", "tel:+16509186756" %> <br>
                <%= link_to "richardjlo.com", root_path %> / 
                <%= link_to "richardjlo", "http://twitter.com/richardjlo" , :target => "_blank"%>
                </p>
            </div>                      
        </div> 
        <div class="clear h-line"></div>     
        <div class="category">        
            <div class="category-title">
                <h2><span class="italic">Education</span></h2>
            </div>
            <div class ="category-content">
                <div class="section">
                    <div class="position">
                        <h2>Stanford University - Stanford, California</h2>
                        <h3>BS Symbolic Systems 2011 - Human Computer Interaction</h3>       
                        <h3>Coursework: Computer Science, Psychology, Persuasion</h3>
                    </div>
                </div>
            </div>
        </div>  
        <div class="clear h-line"></div> 
        <div class="category">        
            <div class="category-title">
                <h2><span class="italic">Work Experience</span></h2>
            </div>
            <div class="category-content">
                <div class="section">
                    <div class="position">
                        <h2>Design Consultant</h2>
                        <h3>Richard Lo LLC</h3>
                    </div>
                    <div class="city">
                        <h3>San Francisco, CA | 1/2011 – Present</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                            <li>- Richard Lo LLC specializes in behavioral and UX design consulting for technology startups</li>                                
                            <li>- Provided heuristic analysis, wireframes, development, and user testing for web and mobile platforms</li>
                            <li>- Designed behavioral strategy to increase customer acquisition, retention, and virality</li>                                
                        </ul>
                    </div>
                </div>  
                <div class="clear h-line"></div>
                <div class="section">
                    <div class="position">
                        <h2>Global Venture Development Director</h2>    
                        <h3>Rocket Internet</h3>
                    </div>
                    <div class="city">
                        <h3>Manila, Philippines | 1/2012 – 3/2012</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                            <li>- Established e-commerce platform, lazada.com.ph, in Philippines</li>
                            <li>- Managed operations and recruiting</li>
                            <li>- Led product management and localization</li>                                
                        </ul>
                    </div>   
                </div>
                <div class="clear h-line"></div>

                <div class="section">
                    <div class="position">
                        <h2>Behavior Designer</h2>    
                        <h3>Spring Health</h3>
                    </div>
                    <div class="city">
                        <h3>Bangalore, India | 10/2011 – 11/2011</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                          <li>- Conducted user interviews with local villagers in Orissa, India</li>
                            <li>- Designed interventions to modify water consumption behaviors in rural villages</li>
                            <li>- Trained under BJ Fogg in the Stanford Persuasive Technology Lab</li>                           
                        </ul>
                    </div>    
                </div>


                <div class="clear h-line"></div>
                <div class="section">
                    <div class="position">
                        <h2>Cofounder</h2>    
                        <h3>Grub Grab</h3>
                    </div>
                    <div class="city">
                        <h3>Palo Alto, CA | 9/2009 – 9/2010</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                          <li>- Defined product roadmap for online food ordering site</li>
                            <li>- Responsible for customer development and partner relations with local restaurants</li>
                            <li>- Led UX strategy for mobile and web designs</li>
                        </ul>
                    </div>    
                </div>             


                <div class="clear h-line"></div>
                <div class="section">
                    <div class="position">
                        <h2>Summer Associate</h2>    
                        <h3>XG Ventures</h3>
                    </div>
                    <div class="city">
                        <h3>Palo Alto, CA | 5/2009 – 9/2010</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                            <li>- Conducted product testing and due diligence for potential investments</li>
                            <li>- Evaluated seed investment opportunities in consumer internet, mobile, and online gaming</li>                                                        
                        </ul>
                    </div> 
                </div>
            </div>
        </div>   
        <div class="clear h-line"></div>     
        <div class="category">
            <div class="category-title">
                <h2><span class="italic">Leadership &amp<br/>Activities</span></h2>
            </div>            
            <div class="category-content">
                <div class="section">
                    <div class="position">
                        <h2>President</h2>    
                        <h3>Alpha Kappa Psi Professional Business Fraternity</h3>
                    </div>
                    <div class="city">
                        <h3>Stanford, CA | 4/2008 – 1/2009</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                            <li>- Identified chapter issues through focus groups and individual feedback sessions</li>                             
                            <li>- Restructured fraternity policies to build a strong community of professionalism and brotherhood</li>  
                            <li>- Reduced number of events, focusing on member attendance and engagement rather than quantity of events hosted</li>                                
                        </ul>
                    </div>
                </div>
                <div class="clear h-line"></div>
                <div class="section">                    
                    <div class="position">
                        <h2>Financial Manager</h2>    
                        <h3>Storey House</h3>
                    </div>
                    <div class="city">
                        <h3>Stanford, CA | 8/2010 – 6/2011</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                            <li>- Managed yearly budget of $200,000 for community of 50 Stanford residents</li>
                            <li>- Led academic, social, and recreational house events</li>
                        </ul>
                    </div> 
                </div>               
                <div class="clear h-line"></div>
                <div class="section last"> 
                    <div class="position">
                        <h2>VP Business Development</h2>    
                        <h3>BASES Stanford Entrepreneurial Society</h3>
                    </div>
                    <div class="city">
                        <h3>Stanford, CA | 12/2007 – 6/2010</h3>
                    </div>
                    <div class="clear"></div>
                    <div class ="details">
                        <ul>
                            <li>- Organized 2 of the largest business plan competitions in the world</li>
                            <li>- Designed entrepreneurial curriculum students interested in starting their own business</li>
                            <li>- Negotiated partnerships with top Silicon Valley VC's including Andreessen Horowitz, NEA, &amp Sequoia Capital</li>
                        </ul>
                    </div>
                </div>


            </div>
        </div> 
        <div class="clear h-line"></div>                
        
        <div class="footer-contact">
            
            <div>
                <p>
                    Richard Lo — 
                    richardjosonlo [at] gmail [dot] com — 
                    <a href="tel:+16509186756">650.918.6756</a>
                </p>
            </div>
        </div>
    </div>                                                                          
</div>         